"""empty message

Revision ID: 01caad7386b1
Revises: d50ec43fb3d7
Create Date: 2020-06-02 01:08:13.499022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01caad7386b1'
down_revision = 'd50ec43fb3d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Tasks', sa.Column('email', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Tasks', 'email')
    # ### end Alembic commands ###
