"""empty message

Revision ID: 07d2535fbdec
Revises: 
Create Date: 2020-05-17 13:18:44.136804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07d2535fbdec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_header', sa.String(length=150), nullable=True),
    sa.Column('task_description', sa.Text(), nullable=True),
    sa.Column('task_type', sa.String(length=50), nullable=True),
    sa.Column('task_priority', sa.String(length=50), nullable=True),
    sa.Column('task_points', sa.Integer(), nullable=True),
    sa.Column('task_status', sa.String(length=50), nullable=True),
    sa.Column('task_is_archived', sa.Boolean(), nullable=True),
    sa.Column('task_due_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Tasks')
    # ### end Alembic commands ###
