"""empty message

Revision ID: 286df5f3a9cd
Revises: e0cc0df873b6
Create Date: 2020-05-29 13:41:21.668612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '286df5f3a9cd'
down_revision = 'e0cc0df873b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Tasks', sa.Column('task_due_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Tasks', 'task_due_date')
    # ### end Alembic commands ###
