"""empty message

Revision ID: 4d7af2d2b846
Revises: af63caff22eb
Create Date: 2020-06-02 12:12:41.862388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d7af2d2b846'
down_revision = 'af63caff22eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Tasks', sa.Column('email', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Tasks', 'email')
    # ### end Alembic commands ###
