"""empty message

Revision ID: af63caff22eb
Revises: 01caad7386b1
Create Date: 2020-06-02 01:14:23.442935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af63caff22eb'
down_revision = '01caad7386b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Tasks', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Tasks', sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
