"""empty message

Revision ID: b82200962218
Revises: e71304b8ea64
Create Date: 2020-06-01 23:43:25.620549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b82200962218'
down_revision = 'e71304b8ea64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('admins_id_key', 'admins', type_='unique')
    op.drop_column('admins', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_unique_constraint('admins_id_key', 'admins', ['id'])
    # ### end Alembic commands ###
