"""empty message

Revision ID: d50ec43fb3d7
Revises: b82200962218
Create Date: 2020-06-01 23:45:02.453298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd50ec43fb3d7'
down_revision = 'b82200962218'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'admins', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'admins', type_='unique')
    op.drop_column('admins', 'id')
    # ### end Alembic commands ###
