"""empty message

Revision ID: dc60b59c2480
Revises: be624582c3b9
Create Date: 2020-06-01 00:22:30.346203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc60b59c2480'
down_revision = 'be624582c3b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Tasks', sa.Column('task_due_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Tasks', 'task_due_date')
    # ### end Alembic commands ###
