"""empty message

Revision ID: e0cc0df873b6
Revises: 
Create Date: 2020-05-29 13:40:56.232147

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e0cc0df873b6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Tasks', 'task_due_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Tasks', sa.Column('task_due_date', postgresql.TIME(precision=6), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
