"""empty message

Revision ID: e71304b8ea64
Revises: dc60b59c2480
Create Date: 2020-06-01 14:12:47.228468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e71304b8ea64'
down_revision = 'dc60b59c2480'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=500), nullable=False),
    sa.Column('phone_number', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('gender', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('email'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_admins_username'), 'admins', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_admins_username'), table_name='admins')
    op.drop_table('admins')
    # ### end Alembic commands ###
